name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: "8.10.3"
        cabal-version: "3.2"
    - name: Setup stack
      run: stack setup
    - name: Build
      run: stack build
